# coding: utf-8

"""
    Rapid

    EPS Rapid V2.3  # noqa: E501

    OpenAPI spec version: 2.3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import eps_rapid
from eps_rapid.models.property_availability_without_score_promotions import PropertyAvailabilityWithoutScorePromotions  # noqa: E501
from eps_rapid.rest import ApiException


class TestPropertyAvailabilityWithoutScorePromotions(unittest.TestCase):
    """PropertyAvailabilityWithoutScorePromotions unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPropertyAvailabilityWithoutScorePromotions(self):
        """Test PropertyAvailabilityWithoutScorePromotions"""
        # FIXME: construct object with mandatory attributes with example values
        # model = eps_rapid.models.property_availability_without_score_promotions.PropertyAvailabilityWithoutScorePromotions()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
