# coding: utf-8

"""
    Rapid

    EPS Rapid V2.3  # noqa: E501

    OpenAPI spec version: 2.3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import eps_rapid
from eps_rapid.models.create_itinerary import CreateItinerary  # noqa: E501
from eps_rapid.rest import ApiException


class TestCreateItinerary(unittest.TestCase):
    """CreateItinerary unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCreateItinerary(self):
        """Test CreateItinerary"""
        # FIXME: construct object with mandatory attributes with example values
        # model = eps_rapid.models.create_itinerary.CreateItinerary()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
