# coding: utf-8

"""
    Rapid

    EPS Rapid V2.3  # noqa: E501

    OpenAPI spec version: 2.3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import eps_rapid
from eps_rapid.models.billing_contact import BillingContact  # noqa: E501
from eps_rapid.rest import ApiException


class TestBillingContact(unittest.TestCase):
    """BillingContact unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBillingContact(self):
        """Test BillingContact"""
        # FIXME: construct object with mandatory attributes with example values
        # model = eps_rapid.models.billing_contact.BillingContact()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
