# coding: utf-8

"""
    Rapid

    EPS Rapid V2.3  # noqa: E501

    OpenAPI spec version: 2.3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import eps_rapid
from eps_rapid.api.manage_bookings_api import ManageBookingsApi  # noqa: E501
from eps_rapid.rest import ApiException


class TestManageBookingsApi(unittest.TestCase):
    """ManageBookingsApi unit test stubs"""

    def setUp(self):
        self.api = eps_rapid.api.manage_bookings_api.ManageBookingsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_itineraries_get(self):
        """Test case for itineraries_get

        Retrieve Booking with Affiliate Reference Id  # noqa: E501
        """
        pass

    def test_itineraries_itinerary_id_delete(self):
        """Test case for itineraries_itinerary_id_delete

        Cancel Held Booking  # noqa: E501
        """
        pass

    def test_itineraries_itinerary_id_get(self):
        """Test case for itineraries_itinerary_id_get

        Retrieve Booking  # noqa: E501
        """
        pass

    def test_itineraries_itinerary_id_rooms_room_id_delete(self):
        """Test case for itineraries_itinerary_id_rooms_room_id_delete

        Cancel a room.  # noqa: E501
        """
        pass

    def test_itineraries_itinerary_id_rooms_room_id_put(self):
        """Test case for itineraries_itinerary_id_rooms_room_id_put

        Change details of a room.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
