# coding: utf-8

"""
    Rapid

    EPS Rapid V2.3  # noqa: E501

    OpenAPI spec version: 2.3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import eps_rapid
from eps_rapid.api.content_api import ContentApi  # noqa: E501
from eps_rapid.rest import ApiException


class TestContentApi(unittest.TestCase):
    """ContentApi unit test stubs"""

    def setUp(self):
        self.api = eps_rapid.api.content_api.ContentApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_chains_get(self):
        """Test case for chains_get

        Chain Reference  # noqa: E501
        """
        pass

    def test_files_properties_catalog_get(self):
        """Test case for files_properties_catalog_get

        Property Catalog File  # noqa: E501
        """
        pass

    def test_files_properties_content_get(self):
        """Test case for files_properties_content_get

        Property Content File  # noqa: E501
        """
        pass

    def test_properties_content_get(self):
        """Test case for properties_content_get

        Property Content  # noqa: E501
        """
        pass

    def test_properties_property_id_guest_reviews_get(self):
        """Test case for properties_property_id_guest_reviews_get

        Property Guest Reviews  # noqa: E501
        """
        pass

    def test_properties_tripadvisor_get(self):
        """Test case for properties_tripadvisor_get

        Property TripAdvisor Information  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
