# coding: utf-8

"""
    Rapid

    EPS Rapid V2.3  # noqa: E501

    OpenAPI spec version: 2.3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import eps_rapid
from eps_rapid.models.rate_content import RateContent  # noqa: E501
from eps_rapid.rest import ApiException


class TestRateContent(unittest.TestCase):
    """RateContent unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRateContent(self):
        """Test RateContent"""
        # FIXME: construct object with mandatory attributes with example values
        # model = eps_rapid.models.rate_content.RateContent()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
