# coding: utf-8

"""
    Rapid

    EPS Rapid V2.3  # noqa: E501

    OpenAPI spec version: 2.3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class AirportAssociatedRegion(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'type': 'str',
        'name': 'str',
        'name_full': 'str',
        'descriptor': 'str',
        'property_ids': 'list[str]'
    }

    attribute_map = {
        'id': 'id',
        'type': 'type',
        'name': 'name',
        'name_full': 'name_full',
        'descriptor': 'descriptor',
        'property_ids': 'property_ids'
    }

    def __init__(self, id=None, type=None, name=None, name_full=None, descriptor=None, property_ids=None):  # noqa: E501
        """AirportAssociatedRegion - a model defined in Swagger"""  # noqa: E501

        self._id = None
        self._type = None
        self._name = None
        self._name_full = None
        self._descriptor = None
        self._property_ids = None
        self.discriminator = None

        if id is not None:
            self.id = id
        if type is not None:
            self.type = type
        if name is not None:
            self.name = name
        if name_full is not None:
            self.name_full = name_full
        if descriptor is not None:
            self.descriptor = descriptor
        if property_ids is not None:
            self.property_ids = property_ids

    @property
    def id(self):
        """Gets the id of this AirportAssociatedRegion.  # noqa: E501

        Region Id of the city or multi-city typically associated with the airport.  # noqa: E501

        :return: The id of this AirportAssociatedRegion.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this AirportAssociatedRegion.

        Region Id of the city or multi-city typically associated with the airport.  # noqa: E501

        :param id: The id of this AirportAssociatedRegion.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def type(self):
        """Gets the type of this AirportAssociatedRegion.  # noqa: E501

        Region type of the associated region.  # noqa: E501

        :return: The type of this AirportAssociatedRegion.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this AirportAssociatedRegion.

        Region type of the associated region.  # noqa: E501

        :param type: The type of this AirportAssociatedRegion.  # noqa: E501
        :type: str
        """

        self._type = type

    @property
    def name(self):
        """Gets the name of this AirportAssociatedRegion.  # noqa: E501

        Region name of the associated region.  # noqa: E501

        :return: The name of this AirportAssociatedRegion.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this AirportAssociatedRegion.

        Region name of the associated region.  # noqa: E501

        :param name: The name of this AirportAssociatedRegion.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def name_full(self):
        """Gets the name_full of this AirportAssociatedRegion.  # noqa: E501

        Full region name of the associated region.  # noqa: E501

        :return: The name_full of this AirportAssociatedRegion.  # noqa: E501
        :rtype: str
        """
        return self._name_full

    @name_full.setter
    def name_full(self, name_full):
        """Sets the name_full of this AirportAssociatedRegion.

        Full region name of the associated region.  # noqa: E501

        :param name_full: The name_full of this AirportAssociatedRegion.  # noqa: E501
        :type: str
        """

        self._name_full = name_full

    @property
    def descriptor(self):
        """Gets the descriptor of this AirportAssociatedRegion.  # noqa: E501

        Specific information about the region e.g. whether it covers surrounding areas for a city. See our [region descriptors reference](https://developer.expediapartnersolutions.com/reference/geography-reference-lists-2-2/) for current known descriptor values.  # noqa: E501

        :return: The descriptor of this AirportAssociatedRegion.  # noqa: E501
        :rtype: str
        """
        return self._descriptor

    @descriptor.setter
    def descriptor(self, descriptor):
        """Sets the descriptor of this AirportAssociatedRegion.

        Specific information about the region e.g. whether it covers surrounding areas for a city. See our [region descriptors reference](https://developer.expediapartnersolutions.com/reference/geography-reference-lists-2-2/) for current known descriptor values.  # noqa: E501

        :param descriptor: The descriptor of this AirportAssociatedRegion.  # noqa: E501
        :type: str
        """

        self._descriptor = descriptor

    @property
    def property_ids(self):
        """Gets the property_ids of this AirportAssociatedRegion.  # noqa: E501

        An array of property ids within the polygon of the associated region.  # noqa: E501

        :return: The property_ids of this AirportAssociatedRegion.  # noqa: E501
        :rtype: list[str]
        """
        return self._property_ids

    @property_ids.setter
    def property_ids(self, property_ids):
        """Sets the property_ids of this AirportAssociatedRegion.

        An array of property ids within the polygon of the associated region.  # noqa: E501

        :param property_ids: The property_ids of this AirportAssociatedRegion.  # noqa: E501
        :type: list[str]
        """

        self._property_ids = property_ids

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(AirportAssociatedRegion, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AirportAssociatedRegion):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
