# coding: utf-8

"""
    Rapid

    EPS Rapid V2.3  # noqa: E501

    OpenAPI spec version: 2.3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from eps_rapid.models.error_errors import ErrorErrors  # noqa: F401,E501
from eps_rapid.models.error_fields import ErrorFields  # noqa: F401,E501


class Error(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'type': 'str',
        'message': 'str',
        'fields': 'list[ErrorFields]',
        'errors': 'list[ErrorErrors]'
    }

    attribute_map = {
        'type': 'type',
        'message': 'message',
        'fields': 'fields',
        'errors': 'errors'
    }

    def __init__(self, type=None, message=None, fields=None, errors=None):  # noqa: E501
        """Error - a model defined in Swagger"""  # noqa: E501

        self._type = None
        self._message = None
        self._fields = None
        self._errors = None
        self.discriminator = None

        if type is not None:
            self.type = type
        if message is not None:
            self.message = message
        if fields is not None:
            self.fields = fields
        if errors is not None:
            self.errors = errors

    @property
    def type(self):
        """Gets the type of this Error.  # noqa: E501

        The error type.  # noqa: E501

        :return: The type of this Error.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this Error.

        The error type.  # noqa: E501

        :param type: The type of this Error.  # noqa: E501
        :type: str
        """

        self._type = type

    @property
    def message(self):
        """Gets the message of this Error.  # noqa: E501

        A human readable message giving details about this error.  # noqa: E501

        :return: The message of this Error.  # noqa: E501
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message):
        """Sets the message of this Error.

        A human readable message giving details about this error.  # noqa: E501

        :param message: The message of this Error.  # noqa: E501
        :type: str
        """

        self._message = message

    @property
    def fields(self):
        """Gets the fields of this Error.  # noqa: E501

        Details about the specific fields that had an error.  # noqa: E501

        :return: The fields of this Error.  # noqa: E501
        :rtype: list[ErrorFields]
        """
        return self._fields

    @fields.setter
    def fields(self, fields):
        """Sets the fields of this Error.

        Details about the specific fields that had an error.  # noqa: E501

        :param fields: The fields of this Error.  # noqa: E501
        :type: list[ErrorFields]
        """

        self._fields = fields

    @property
    def errors(self):
        """Gets the errors of this Error.  # noqa: E501

        An array of all the actual errors that occured.  # noqa: E501

        :return: The errors of this Error.  # noqa: E501
        :rtype: list[ErrorErrors]
        """
        return self._errors

    @errors.setter
    def errors(self, errors):
        """Sets the errors of this Error.

        An array of all the actual errors that occured.  # noqa: E501

        :param errors: The errors of this Error.  # noqa: E501
        :type: list[ErrorErrors]
        """

        self._errors = errors

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Error, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Error):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
