# coding: utf-8

"""
    Rapid

    EPS Rapid V2.3  # noqa: E501

    OpenAPI spec version: 2.3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class PropertyContentPolicies(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'know_before_you_go': 'str'
    }

    attribute_map = {
        'know_before_you_go': 'know_before_you_go'
    }

    def __init__(self, know_before_you_go=None):  # noqa: E501
        """PropertyContentPolicies - a model defined in Swagger"""  # noqa: E501

        self._know_before_you_go = None
        self.discriminator = None

        if know_before_you_go is not None:
            self.know_before_you_go = know_before_you_go

    @property
    def know_before_you_go(self):
        """Gets the know_before_you_go of this PropertyContentPolicies.  # noqa: E501

        Description of information that may be helpful when planning a trip to this property.  # noqa: E501

        :return: The know_before_you_go of this PropertyContentPolicies.  # noqa: E501
        :rtype: str
        """
        return self._know_before_you_go

    @know_before_you_go.setter
    def know_before_you_go(self, know_before_you_go):
        """Sets the know_before_you_go of this PropertyContentPolicies.

        Description of information that may be helpful when planning a trip to this property.  # noqa: E501

        :param know_before_you_go: The know_before_you_go of this PropertyContentPolicies.  # noqa: E501
        :type: str
        """

        self._know_before_you_go = know_before_you_go

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(PropertyContentPolicies, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PropertyContentPolicies):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
