# coding: utf-8

"""
    Rapid

    EPS Rapid V2.3  # noqa: E501

    OpenAPI spec version: 2.3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class PropertyContentAllInclusive(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'all_rate_plans': 'bool',
        'some_rate_plans': 'bool',
        'details': 'str'
    }

    attribute_map = {
        'all_rate_plans': 'all_rate_plans',
        'some_rate_plans': 'some_rate_plans',
        'details': 'details'
    }

    def __init__(self, all_rate_plans=None, some_rate_plans=None, details=None):  # noqa: E501
        """PropertyContentAllInclusive - a model defined in Swagger"""  # noqa: E501

        self._all_rate_plans = None
        self._some_rate_plans = None
        self._details = None
        self.discriminator = None

        if all_rate_plans is not None:
            self.all_rate_plans = all_rate_plans
        if some_rate_plans is not None:
            self.some_rate_plans = some_rate_plans
        if details is not None:
            self.details = details

    @property
    def all_rate_plans(self):
        """Gets the all_rate_plans of this PropertyContentAllInclusive.  # noqa: E501

        Indicates if all rate plans at the property provide all-inclusive amenities.  # noqa: E501

        :return: The all_rate_plans of this PropertyContentAllInclusive.  # noqa: E501
        :rtype: bool
        """
        return self._all_rate_plans

    @all_rate_plans.setter
    def all_rate_plans(self, all_rate_plans):
        """Sets the all_rate_plans of this PropertyContentAllInclusive.

        Indicates if all rate plans at the property provide all-inclusive amenities.  # noqa: E501

        :param all_rate_plans: The all_rate_plans of this PropertyContentAllInclusive.  # noqa: E501
        :type: bool
        """

        self._all_rate_plans = all_rate_plans

    @property
    def some_rate_plans(self):
        """Gets the some_rate_plans of this PropertyContentAllInclusive.  # noqa: E501

        Indicates if some, but not all, rate plans at the property provide all-inclusive amenities.  # noqa: E501

        :return: The some_rate_plans of this PropertyContentAllInclusive.  # noqa: E501
        :rtype: bool
        """
        return self._some_rate_plans

    @some_rate_plans.setter
    def some_rate_plans(self, some_rate_plans):
        """Sets the some_rate_plans of this PropertyContentAllInclusive.

        Indicates if some, but not all, rate plans at the property provide all-inclusive amenities.  # noqa: E501

        :param some_rate_plans: The some_rate_plans of this PropertyContentAllInclusive.  # noqa: E501
        :type: bool
        """

        self._some_rate_plans = some_rate_plans

    @property
    def details(self):
        """Gets the details of this PropertyContentAllInclusive.  # noqa: E501

        Details about amenities and services included in the all-inclusive rates.  # noqa: E501

        :return: The details of this PropertyContentAllInclusive.  # noqa: E501
        :rtype: str
        """
        return self._details

    @details.setter
    def details(self, details):
        """Sets the details of this PropertyContentAllInclusive.

        Details about amenities and services included in the all-inclusive rates.  # noqa: E501

        :param details: The details of this PropertyContentAllInclusive.  # noqa: E501
        :type: str
        """

        self._details = details

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(PropertyContentAllInclusive, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PropertyContentAllInclusive):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
