# coding: utf-8

"""
    Rapid

    EPS Rapid V2.3  # noqa: E501

    OpenAPI spec version: 2.3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from eps_rapid.models.payment_type import PaymentType  # noqa: F401,E501


class PropertyContentOnsitePayments(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'currency': 'str',
        'types': 'dict(str, PaymentType)'
    }

    attribute_map = {
        'currency': 'currency',
        'types': 'types'
    }

    def __init__(self, currency=None, types=None):  # noqa: E501
        """PropertyContentOnsitePayments - a model defined in Swagger"""  # noqa: E501

        self._currency = None
        self._types = None
        self.discriminator = None

        if currency is not None:
            self.currency = currency
        if types is not None:
            self.types = types

    @property
    def currency(self):
        """Gets the currency of this PropertyContentOnsitePayments.  # noqa: E501

        The currency accepted at the property.  # noqa: E501

        :return: The currency of this PropertyContentOnsitePayments.  # noqa: E501
        :rtype: str
        """
        return self._currency

    @currency.setter
    def currency(self, currency):
        """Sets the currency of this PropertyContentOnsitePayments.

        The currency accepted at the property.  # noqa: E501

        :param currency: The currency of this PropertyContentOnsitePayments.  # noqa: E501
        :type: str
        """

        self._currency = currency

    @property
    def types(self):
        """Gets the types of this PropertyContentOnsitePayments.  # noqa: E501

        The types of payments accepted at the property.  # noqa: E501

        :return: The types of this PropertyContentOnsitePayments.  # noqa: E501
        :rtype: dict(str, PaymentType)
        """
        return self._types

    @types.setter
    def types(self, types):
        """Sets the types of this PropertyContentOnsitePayments.

        The types of payments accepted at the property.  # noqa: E501

        :param types: The types of this PropertyContentOnsitePayments.  # noqa: E501
        :type: dict(str, PaymentType)
        """

        self._types = types

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(PropertyContentOnsitePayments, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PropertyContentOnsitePayments):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
