# coding: utf-8

"""
    Rapid

    EPS Rapid V2.3  # noqa: E501

    OpenAPI spec version: 2.3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class PropertyContentRatingsGuest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'count': 'float',
        'average': 'str'
    }

    attribute_map = {
        'count': 'count',
        'average': 'average'
    }

    def __init__(self, count=None, average=None):  # noqa: E501
        """PropertyContentRatingsGuest - a model defined in Swagger"""  # noqa: E501

        self._count = None
        self._average = None
        self.discriminator = None

        if count is not None:
            self.count = count
        if average is not None:
            self.average = average

    @property
    def count(self):
        """Gets the count of this PropertyContentRatingsGuest.  # noqa: E501

        A count of all of the guest review ratings which currently exist for this property.  # noqa: E501

        :return: The count of this PropertyContentRatingsGuest.  # noqa: E501
        :rtype: float
        """
        return self._count

    @count.setter
    def count(self, count):
        """Sets the count of this PropertyContentRatingsGuest.

        A count of all of the guest review ratings which currently exist for this property.  # noqa: E501

        :param count: The count of this PropertyContentRatingsGuest.  # noqa: E501
        :type: float
        """

        self._count = count

    @property
    def average(self):
        """Gets the average of this PropertyContentRatingsGuest.  # noqa: E501

        Overall rating for the property averaged from all guest reviews. Returns a value between 1.0 and 5.0.  # noqa: E501

        :return: The average of this PropertyContentRatingsGuest.  # noqa: E501
        :rtype: str
        """
        return self._average

    @average.setter
    def average(self, average):
        """Sets the average of this PropertyContentRatingsGuest.

        Overall rating for the property averaged from all guest reviews. Returns a value between 1.0 and 5.0.  # noqa: E501

        :param average: The average of this PropertyContentRatingsGuest.  # noqa: E501
        :type: str
        """

        self._average = average

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(PropertyContentRatingsGuest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PropertyContentRatingsGuest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
