# coding: utf-8

"""
    Rapid

    EPS Rapid V2.3  # noqa: E501

    OpenAPI spec version: 2.3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from eps_rapid.models.attribute import Attribute  # noqa: F401,E501


class PropertyContentAttributes(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'general': 'dict(str, Attribute)',
        'pets': 'dict(str, Attribute)'
    }

    attribute_map = {
        'general': 'general',
        'pets': 'pets'
    }

    def __init__(self, general=None, pets=None):  # noqa: E501
        """PropertyContentAttributes - a model defined in Swagger"""  # noqa: E501

        self._general = None
        self._pets = None
        self.discriminator = None

        if general is not None:
            self.general = general
        if pets is not None:
            self.pets = pets

    @property
    def general(self):
        """Gets the general of this PropertyContentAttributes.  # noqa: E501

        Lists all of the general attributes about the property.  # noqa: E501

        :return: The general of this PropertyContentAttributes.  # noqa: E501
        :rtype: dict(str, Attribute)
        """
        return self._general

    @general.setter
    def general(self, general):
        """Sets the general of this PropertyContentAttributes.

        Lists all of the general attributes about the property.  # noqa: E501

        :param general: The general of this PropertyContentAttributes.  # noqa: E501
        :type: dict(str, Attribute)
        """

        self._general = general

    @property
    def pets(self):
        """Gets the pets of this PropertyContentAttributes.  # noqa: E501

        Lists all of the pet attributes about the property.  # noqa: E501

        :return: The pets of this PropertyContentAttributes.  # noqa: E501
        :rtype: dict(str, Attribute)
        """
        return self._pets

    @pets.setter
    def pets(self, pets):
        """Sets the pets of this PropertyContentAttributes.

        Lists all of the pet attributes about the property.  # noqa: E501

        :param pets: The pets of this PropertyContentAttributes.  # noqa: E501
        :type: dict(str, Attribute)
        """

        self._pets = pets

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(PropertyContentAttributes, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PropertyContentAttributes):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
