# coding: utf-8

"""
    Rapid

    EPS Rapid V2.3  # noqa: E501

    OpenAPI spec version: 2.3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class RetrieveRateFees(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'type': 'str',
        'value': 'str',
        'currency': 'str',
        'scope': 'str',
        'frequency': 'str'
    }

    attribute_map = {
        'type': 'type',
        'value': 'value',
        'currency': 'currency',
        'scope': 'scope',
        'frequency': 'frequency'
    }

    def __init__(self, type=None, value=None, currency=None, scope=None, frequency=None):  # noqa: E501
        """RetrieveRateFees - a model defined in Swagger"""  # noqa: E501

        self._type = None
        self._value = None
        self._currency = None
        self._scope = None
        self._frequency = None
        self.discriminator = None

        if type is not None:
            self.type = type
        if value is not None:
            self.value = value
        if currency is not None:
            self.currency = currency
        if scope is not None:
            self.scope = scope
        if frequency is not None:
            self.frequency = frequency

    @property
    def type(self):
        """Gets the type of this RetrieveRateFees.  # noqa: E501

        The type of fee.  # noqa: E501

        :return: The type of this RetrieveRateFees.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this RetrieveRateFees.

        The type of fee.  # noqa: E501

        :param type: The type of this RetrieveRateFees.  # noqa: E501
        :type: str
        """
        allowed_values = ["resort_fee", "mandatory_tax", "mandatory_fee"]  # noqa: E501
        if type not in allowed_values:
            raise ValueError(
                "Invalid value for `type` ({0}), must be one of {1}"  # noqa: E501
                .format(type, allowed_values)
            )

        self._type = type

    @property
    def value(self):
        """Gets the value of this RetrieveRateFees.  # noqa: E501

        The amount of the fee.  # noqa: E501

        :return: The value of this RetrieveRateFees.  # noqa: E501
        :rtype: str
        """
        return self._value

    @value.setter
    def value(self, value):
        """Sets the value of this RetrieveRateFees.

        The amount of the fee.  # noqa: E501

        :param value: The value of this RetrieveRateFees.  # noqa: E501
        :type: str
        """

        self._value = value

    @property
    def currency(self):
        """Gets the currency of this RetrieveRateFees.  # noqa: E501

        The currency of the fee.  # noqa: E501

        :return: The currency of this RetrieveRateFees.  # noqa: E501
        :rtype: str
        """
        return self._currency

    @currency.setter
    def currency(self, currency):
        """Sets the currency of this RetrieveRateFees.

        The currency of the fee.  # noqa: E501

        :param currency: The currency of this RetrieveRateFees.  # noqa: E501
        :type: str
        """

        self._currency = currency

    @property
    def scope(self):
        """Gets the scope of this RetrieveRateFees.  # noqa: E501

        The scope of the fee.  # noqa: E501

        :return: The scope of this RetrieveRateFees.  # noqa: E501
        :rtype: str
        """
        return self._scope

    @scope.setter
    def scope(self, scope):
        """Sets the scope of this RetrieveRateFees.

        The scope of the fee.  # noqa: E501

        :param scope: The scope of this RetrieveRateFees.  # noqa: E501
        :type: str
        """
        allowed_values = ["unknown", "per_person", "per_room", "per_accommodation", "per_house", "per_apartment", "per_adult"]  # noqa: E501
        if scope not in allowed_values:
            raise ValueError(
                "Invalid value for `scope` ({0}), must be one of {1}"  # noqa: E501
                .format(scope, allowed_values)
            )

        self._scope = scope

    @property
    def frequency(self):
        """Gets the frequency of this RetrieveRateFees.  # noqa: E501

        The frequency of the fee.  # noqa: E501

        :return: The frequency of this RetrieveRateFees.  # noqa: E501
        :rtype: str
        """
        return self._frequency

    @frequency.setter
    def frequency(self, frequency):
        """Sets the frequency of this RetrieveRateFees.

        The frequency of the fee.  # noqa: E501

        :param frequency: The frequency of this RetrieveRateFees.  # noqa: E501
        :type: str
        """
        allowed_values = ["unknown", "per_night", "per_day", "per_stay", "per_week", "round_trip", "one_way"]  # noqa: E501
        if frequency not in allowed_values:
            raise ValueError(
                "Invalid value for `frequency` ({0}), must be one of {1}"  # noqa: E501
                .format(frequency, allowed_values)
            )

        self._frequency = frequency

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(RetrieveRateFees, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, RetrieveRateFees):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
