# coding: utf-8

"""
    Rapid

    EPS Rapid V2.3  # noqa: E501

    OpenAPI spec version: 2.3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from eps_rapid.models.link import Link  # noqa: F401,E501


class TripAdvisor(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'property_id': 'str',
        'tripadvisor_id': 'str',
        'rating': 'str',
        'count': 'float',
        'links': 'dict(str, Link)'
    }

    attribute_map = {
        'property_id': 'property_id',
        'tripadvisor_id': 'tripadvisor_id',
        'rating': 'rating',
        'count': 'count',
        'links': 'links'
    }

    def __init__(self, property_id=None, tripadvisor_id=None, rating=None, count=None, links=None):  # noqa: E501
        """TripAdvisor - a model defined in Swagger"""  # noqa: E501

        self._property_id = None
        self._tripadvisor_id = None
        self._rating = None
        self._count = None
        self._links = None
        self.discriminator = None

        if property_id is not None:
            self.property_id = property_id
        if tripadvisor_id is not None:
            self.tripadvisor_id = tripadvisor_id
        if rating is not None:
            self.rating = rating
        if count is not None:
            self.count = count
        if links is not None:
            self.links = links

    @property
    def property_id(self):
        """Gets the property_id of this TripAdvisor.  # noqa: E501

        Unique Expedia property ID.  # noqa: E501

        :return: The property_id of this TripAdvisor.  # noqa: E501
        :rtype: str
        """
        return self._property_id

    @property_id.setter
    def property_id(self, property_id):
        """Sets the property_id of this TripAdvisor.

        Unique Expedia property ID.  # noqa: E501

        :param property_id: The property_id of this TripAdvisor.  # noqa: E501
        :type: str
        """

        self._property_id = property_id

    @property
    def tripadvisor_id(self):
        """Gets the tripadvisor_id of this TripAdvisor.  # noqa: E501

        Unique TripAdvisor property ID. Can be used for mapping properties across suppliers.  # noqa: E501

        :return: The tripadvisor_id of this TripAdvisor.  # noqa: E501
        :rtype: str
        """
        return self._tripadvisor_id

    @tripadvisor_id.setter
    def tripadvisor_id(self, tripadvisor_id):
        """Sets the tripadvisor_id of this TripAdvisor.

        Unique TripAdvisor property ID. Can be used for mapping properties across suppliers.  # noqa: E501

        :param tripadvisor_id: The tripadvisor_id of this TripAdvisor.  # noqa: E501
        :type: str
        """

        self._tripadvisor_id = tripadvisor_id

    @property
    def rating(self):
        """Gets the rating of this TripAdvisor.  # noqa: E501

        TripAdvisor rating for the property. Returns a value between 1.0 and 5.0.  # noqa: E501

        :return: The rating of this TripAdvisor.  # noqa: E501
        :rtype: str
        """
        return self._rating

    @rating.setter
    def rating(self, rating):
        """Sets the rating of this TripAdvisor.

        TripAdvisor rating for the property. Returns a value between 1.0 and 5.0.  # noqa: E501

        :param rating: The rating of this TripAdvisor.  # noqa: E501
        :type: str
        """

        self._rating = rating

    @property
    def count(self):
        """Gets the count of this TripAdvisor.  # noqa: E501

        Number of TripAdvisor guest reviews for the property. Only provided when greater than zero.  # noqa: E501

        :return: The count of this TripAdvisor.  # noqa: E501
        :rtype: float
        """
        return self._count

    @count.setter
    def count(self, count):
        """Sets the count of this TripAdvisor.

        Number of TripAdvisor guest reviews for the property. Only provided when greater than zero.  # noqa: E501

        :param count: The count of this TripAdvisor.  # noqa: E501
        :type: float
        """

        self._count = count

    @property
    def links(self):
        """Gets the links of this TripAdvisor.  # noqa: E501

        Link to the TripAdvisor rating image. Display of the rating image is required per TripAdvisor’s contract.  # noqa: E501

        :return: The links of this TripAdvisor.  # noqa: E501
        :rtype: dict(str, Link)
        """
        return self._links

    @links.setter
    def links(self, links):
        """Sets the links of this TripAdvisor.

        Link to the TripAdvisor rating image. Display of the rating image is required per TripAdvisor’s contract.  # noqa: E501

        :param links: The links of this TripAdvisor.  # noqa: E501
        :type: dict(str, Link)
        """

        self._links = links

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(TripAdvisor, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, TripAdvisor):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
